---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/hhatto/autopep8
    rev: 'v2.0.4'
    hooks:
      - id: autopep8

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-toml

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.8.0"
    hooks:
      - id: mypy
        additional_dependencies:
          - "click>=8.0.3,!=8.1.4"
          - "attrs>=20.3.0"
          - "ruamel.yaml>=0.16.6"
          - "jinja2>=2.11.3"
        pass_filenames: false
        args: [--config-file=pyproject.toml]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.11
    hooks:
      - id: ruff
        args:
          - '--fix'
          - '--show-fixes'

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.1
    hooks:
      - id: gitleaks
