---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/hhatto/autopep8
    rev: 'v2.3.1'
    hooks:
      - id: autopep8

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-toml

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.14.1"
    hooks:
      - id: mypy
        additional_dependencies:
          - "click>=8.0.3,!=8.1.4"
          - "attrs>=20.3.0"
          - "ruamel.yaml>=0.16.6"
          - "jinja2>=2.11.3"
          # prevent conflict between types-requests and urllib3
          - "types-requests<2.31.0.7; python_version < '3.10'"
          - "types-requests; python_version >= '3.10'"

        pass_filenames: false
        args: [--config-file=pyproject.toml]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.9.1
    hooks:
      - id: ruff
        args:
          - '--fix'
          - '--show-fixes'

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.23.0
    hooks:
      - id: gitleaks

  # Backstage linter
  # https://console.one.redhat.com/docs/quality-community/Component/qe-toolbelt-catalog/onboarding/#pre-commit
  - repo: local
    hooks:
      - id: backstage-entity-validator
        name: backstage-entity-validator
        language: system
        files: catalog-info\.yaml$
        entry: npx @roadiehq/backstage-entity-validator validate-entity
        exclude: |
          (?x)^(
            user_repo.*
          )$
