"""Newa - Test automation and reporting tool."""

from __future__ import annotations

# Import all models
from newa.models import (
    EVENT_FILE_PREFIX,
    EXECUTE_FILE_PREFIX,
    INIT_FILE_PREFIX,
    JIRA_FILE_PREFIX,
    SCHEDULE_FILE_PREFIX,
    STATEDIR_TOPDIR,
    TF_REQUEST_FINISHED_STATES,
    UNDEFINED_COMPOSE,
    Arch,
    ArtifactJob,
    CLIContext,
    Cloneable,
    Compose,
    Erratum,
    ErratumCommentTrigger,
    ErratumContentType,
    Event,
    EventJob,
    EventType,
    ExecuteHow,
    ExecuteJob,
    Execution,
    InitialErratum,
    Issue,
    IssueAction,
    IssueConfig,
    IssueTransitions,
    IssueType,
    JiraJob,
    OnRespinAction,
    RawRecipeConfigDimension,
    RawRecipeConfigDimensions,
    RawRecipeReportPortalConfigDimension,
    RawRecipeTFConfigDimension,
    RawRecipeTmtConfigDimension,
    Recipe,
    RecipeConfig,
    RecipeContext,
    RecipeEnvironment,
    ReportPortalAttributes,
    Request,
    RequestResult,
    RoG,
    ScheduleJob,
    Serializable,
    Settings,
    TFRequest,
    check_tf_cli_version,
    )

# Import all services
from newa.services import (
    ErrataTool,
    IssueHandler,
    JiraField,
    JiraIssueLinkType,
    ReportPortal,
    RoGTool,
    )

# Import all utilities
from newa.utils import (
    NSVCParser,
    NVRParser,
    ResponseContentType,
    default_template_environment,
    eval_test,
    get_request,
    get_url_basename,
    post_request,
    render_template,
    short_sleep,
    yaml_parser,
    )

__all__ = [
    'EVENT_FILE_PREFIX',
    'EXECUTE_FILE_PREFIX',
    'INIT_FILE_PREFIX',
    'JIRA_FILE_PREFIX',
    'SCHEDULE_FILE_PREFIX',
    'STATEDIR_TOPDIR',
    'TF_REQUEST_FINISHED_STATES',
    'UNDEFINED_COMPOSE',
    # Models - base
    'Arch',
    # Models - jobs
    'ArtifactJob',
    # Models - settings
    'CLIContext',
    'Cloneable',
    # Models - artifacts
    'Compose',
    # Services
    'ErrataTool',
    'Erratum',
    'ErratumCommentTrigger',
    'ErratumContentType',
    # Models - events
    'Event',
    'EventJob',
    'EventType',
    'ExecuteHow',
    'ExecuteJob',
    # Models - execution
    'Execution',
    'InitialErratum',
    # Models - issues
    'Issue',
    'IssueAction',
    'IssueConfig',
    'IssueHandler',
    'IssueTransitions',
    'IssueType',
    'JiraField',
    'JiraIssueLinkType',
    'JiraJob',
    # Utils
    'NSVCParser',
    'NVRParser',
    'OnRespinAction',
    # Models - recipes
    'RawRecipeConfigDimension',
    'RawRecipeConfigDimensions',
    'RawRecipeReportPortalConfigDimension',
    'RawRecipeTFConfigDimension',
    'RawRecipeTmtConfigDimension',
    'Recipe',
    'RecipeConfig',
    'RecipeContext',
    'RecipeEnvironment',
    'ReportPortal',
    'ReportPortalAttributes',
    'Request',
    'RequestResult',
    'ResponseContentType',
    'RoG',
    'RoGTool',
    'ScheduleJob',
    'Serializable',
    'Settings',
    'TFRequest',
    'check_tf_cli_version',
    'default_template_environment',
    'eval_test',
    'get_request',
    'get_url_basename',
    'post_request',
    'render_template',
    'short_sleep',
    'yaml_parser',
    ]
